config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :pages, only: %i[home show]

  devise_for :users

  resources :gardens do
    member do
      post 'add_to_garden', to: 'gardens#add_to_garden', as: 'add_to_garden'
      delete 'remove_from_garden', to: 'gardens#remove_from_garden'
    end
    resources :recommendations, only: %i[index create show]
    resources :plants, only: %i[index show destroy]
  end

  resources :resources, only: %i[index show]
  # resources :chat, only: %i[index show]
  get 'chat/index'
  post 'chat', to: 'chat#chat'
  resources :forums, only: %i[index show] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :garden_plants
  has_many :plants, through: :garden_plants
  has_many :recommendations

  include PgSearch::Model

  pg_search_scope :search_by_plant_name,
    against: [ :plant_name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/garden_plant.rb
class GardenPlant < ApplicationRecord
  belongs_to :garden
  belongs_to :plant
  belongs_to :user
end

app/models/massage.rb
class Massage < ApplicationRecord
  belongs_to :forum
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :forum
  belongs_to :user

  def sender?(a_user)
    user.id == a_user.id
  end

end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :garden_plants
  has_many :gardens, through: :garden_plants
  has_many :recommendations

  include PgSearch::Model

  pg_search_scope :search_by_plant_name,
    against: [ :plant_name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :garden
  attribute :sunlight, :decimal
  belongs_to :plant

  # def self.create_from_garden(garden)
  #   # Generate recommendations based on garden parameters
  #   # You can implement your own logic here
  #   recommendations = generate_recommendations(garden)

  #   # Create a new recommendation associated with the garden
  #   recommendation = garden.recommendations.build
  #   recommendation.plants = recommendations
  #   recommendation.save
  # end

  # private

  # def self.generate_recommendations(garden)
  #   # Implement your logic to generate recommendations based on the garden's parameters
  #   # This could involve querying the Plant model based on garden parameters
  #   # and returning a collection of recommended plants

  #   # Example: Return the first 10 plants in the database as recommendations
  #   Plant.limit(10)
  # end
end

app/models/resource.rb
class Resource < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_by_title,
                  against: [:title],
                  using: {
                    tsearch: { prefix: true }, # <-- now `superman batm` will return something!
                  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gardens
  has_many :forums
  has_many :messages
  has_many :user_resources
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_resource.rb
class UserResource < ApplicationRecord
  belongs_to :user
  belongs_to :resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  # before_action :authenticate_user!, except: %i[home]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :email, :password])
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @forum = Forum.all
    @user = current_user
    @user_forum = @forum.where(user_id: @user)
  end

  def show
    @forum = Forum.find(params[:id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @forum = Forum.find(params[:forum_id])
    @message = Message.new(message_params)
    @message.forum = @forum
    @message.user = current_user

    if @message.save
      ForumChannel.broadcast_to(
        @forum,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "forums/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: %i[home show]

  def home
    category = params[:category]

    if params[:query].present?
      @plants = Plant.search_by_plant_name(params[:query])
    else
      @plants = if category.present?
        if category == 'popular'
          Plant.where(popular: true)
        else
          Plant.where(category: category)
        end
      else
        Plant.order(:plant_name)
      end
    end

    puts "Plants count: #{@plants}" # Add this line for debugging
  end

  def show
    @plant = Plant.find(params[:id])
  end

  # Other actions in the PagesController
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show]

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
  end

  private

  def set_plant
    @plant = Plant.find(params[:id])
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @garden = Garden.find(params[:garden_id])
    @recommendations = Recommendation.where(garden_id: @garden.id)
  end

  def show
    @recommendation = Recommendation.find(params[:id])
    # Additional code to render the show page
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:size)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @resources = Resource.all

    # Search

    popular = params[:popular]

    if params[:query].present?
      @resources = Resource.search_by_title(params[:query])
    else
      @resources = if popular.present?
        Resource.where(popular: true)
      else
        Resource.order(:title)
    end
  end
end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <%= image_tag("footer.jpg", alt: "Footer", class: "footer-image") %>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid d-flex align-items-end justify-content-between">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "gropro_name.png", class: "name-image" %>
    <% end %>
    <%= image_tag "pot_plants.png", class: "middle-image" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item <%= "active" if current_page?(root_path) %>">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= "active" if current_page?(gardens_path) %>">
          <%= link_to "Gardens", gardens_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= "active" if current_page?(resources_path) %>">
          <%= link_to "Resources", resources_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(forums_path) %>">
          <%= link_to "Forums", forums_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-bs-toggle="dropdown"><%= current_user.first_name %></a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item <%= "active" if current_page?(new_user_session_path) %>">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div id="gradient-bar"></div>