config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :pages, only: %i[home show]

  devise_for :users

  resources :gardens do
    member do
      post 'add_to_garden', to: 'gardens#add_to_garden', as: 'add_to_garden'
      delete 'remove_from_garden', to: 'gardens#remove_from_garden'
    end
    resources :recommendations, only: %i[index create show]
    resources :plants, only: %i[index show destroy]
  end

  resources :resources, only: %i[index show]
  # resources :chat, only: %i[index show]
  get 'chat/index'
  post 'chat', to: 'chat#chat'
  resources :forums, only: %i[index show] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :garden_plants
  has_many :plants, through: :garden_plants
  has_many :recommendations

  include PgSearch::Model

  pg_search_scope :search_by_plant_name,
    against: [ :plant_name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/garden_plant.rb
class GardenPlant < ApplicationRecord
  belongs_to :garden
  belongs_to :plant
  belongs_to :user
end

app/models/massage.rb
class Massage < ApplicationRecord
  belongs_to :forum
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :forum
  belongs_to :user

  def sender?(a_user)
    user.id == a_user.id
  end

end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :garden_plants
  has_many :gardens, through: :garden_plants
  has_many :recommendations

  include PgSearch::Model

  pg_search_scope :search_by_plant_name,
    against: [ :plant_name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :garden
  attribute :sunlight, :decimal
  belongs_to :plant

  # def self.create_from_garden(garden)
  #   # Generate recommendations based on garden parameters
  #   # You can implement your own logic here
  #   recommendations = generate_recommendations(garden)

  #   # Create a new recommendation associated with the garden
  #   recommendation = garden.recommendations.build
  #   recommendation.plants = recommendations
  #   recommendation.save
  # end

  # private

  # def self.generate_recommendations(garden)
  #   # Implement your logic to generate recommendations based on the garden's parameters
  #   # This could involve querying the Plant model based on garden parameters
  #   # and returning a collection of recommended plants

  #   # Example: Return the first 10 plants in the database as recommendations
  #   Plant.limit(10)
  # end
end

app/models/resource.rb
class Resource < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_by_title,
                  against: [:title],
                  using: {
                    tsearch: { prefix: true }, # <-- now `superman batm` will return something!
                  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gardens
  has_many :forums
  has_many :messages
  has_many :user_resources
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_resource.rb
class UserResource < ApplicationRecord
  belongs_to :user
  belongs_to :resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  # before_action :authenticate_user!, except: %i[home]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :email, :password])
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @forum = Forum.all
    @user = current_user
    @user_forum = @forum.where(user_id: @user)
  end

  def show
    @forum = Forum.find(params[:id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @forum = Forum.find(params[:forum_id])
    @message = Message.new(message_params)
    @message.forum = @forum
    @message.user = current_user

    if @message.save
      ForumChannel.broadcast_to(
        @forum,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "forums/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: %i[home show]

  def home
    category = params[:category]

    if params[:query].present?
      @plants = Plant.search_by_plant_name(params[:query])
    else
      @plants = if category.present?
        if category == 'popular'
          Plant.where(popular: true)
        else
          Plant.where(category: category)
        end
      else
        Plant.order(:plant_name)
      end
    end

    puts "Plants count: #{@plants}" # Add this line for debugging
  end

  def show
    @plant = Plant.find(params[:id])
  end

  # Other actions in the PagesController
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show]

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
  end

  private

  def set_plant
    @plant = Plant.find(params[:id])
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @garden = Garden.find(params[:garden_id])
    @recommendations = Recommendation.where(garden_id: @garden.id)
  end

  def show
    @recommendation = Recommendation.find(params[:id])
    # Additional code to render the show page
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:size)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @resources = Resource.all

    # Search

    popular = params[:popular]

    if params[:query].present?
      @resources = Resource.search_by_title(params[:query])
    else
      @resources = if popular.present?
        Resource.where(popular: true)
      else
        Resource.order(:title)
    end
  end
end

  def show
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gardens/edit.html.erb
<div class="main-container">
  <h1 class="plant-heading">Edit Your Garden</h1>
  <%= form_for @garden, html: { class: 'garden-form' } do |f| %>
    <div class="form-group">
      <%= f.label :name, "Garden Name", class: 'form-label' %>
      <%= f.text_field :name, class: 'form-input', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :location, "Location", class: 'form-label' %>
      <%= f.text_field :location, class: 'form-input', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :outside, "Inside/Outside", class: 'form-label' %>
      <%= f.select :outside, ["Inside", "Outside"], class: 'form-select', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :size, "Garden Size (m2)", class: 'form-label' %>
      <%= f.number_field :size, step: "0.01", class: 'form-input', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :sunlight, "Sunlight Percentage (%)", class: 'form-label' %>
      <%= f.number_field :sunlight, step: "10", class: 'form-input', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :additional_info, "Additional Info", class: 'form-label' %>
      <%= f.text_field :additional_info, class: 'form-input' %>
    </div>
    <div class="form-group">
      <%= f.submit "Update Garden", class: 'form-submit', id: 'update-garden-btn' %>
      </div>
  <% end %>
</div>

app/views/gardens/index.html.erb
<div class="main-container">
<div class="weather-container">
<h2 class="weather-heading">Current Weather</h2>
  <header class="header">
    <div class="header-left">
       <img class="weather-icon large" data-current-icon src="/assets/sun.svg">


      <div class="header-current-temp">
        <span data-current-temp>31</span>&deg;
      </div>
    </div>
    <div class="header-right">
      <div class="info-group">
        <div class="label">High</div>
        <div><span data-current-high>32</span>&deg;
        </div>
      </div>
      <div class="info-group">
        <div class="label">FL High</div>
        <div><span data-current-fl-high>27</span>&deg;
        </div>
      </div>
      <div class="info-group">
        <div class="label">Wind</div>
        <div><span data-current-wind>9</span><span class="value-sub-info">km/h</span>
        </div>
      </div>
      <div class="info-group">
        <div class="label">Low</div>
        <div><span data-current-low>19</span>&deg;
        </div>
      </div>
      <div class="info-group">
        <div class="label">FL Low</div>
        <div><span data-current-fl-low>12</span>&deg;
        </div>
      </div>
      <div class="info-group">
        <div class="label">Precip</div>
        <div>
          <span data-current-precip>0.1</span
            ><span class="value-sub-info">in</span>
        </div>
      </div>
    </div>
  </header>

  <section class="day-section" data-day-section>

  <div class="day-card">
        <%= image_tag "cloud.svg", class:"weather-icon" %>
        <div class="day-card-day">Monday</div>
        <div>32&deg;</div>
      </div>

      <div class="day-card">
        <%= image_tag "cloud.svg", class:"weather-icon" %>
        <div class="day-card-day">Tuesday</div>
        <div>32&deg;</div>
      </div>

      <div class="day-card">
        <%= image_tag "cloud.svg", class:"weather-icon" %>
        <div class="day-card-day">Wednesday</div>
        <div>32&deg;</div>
      </div>

      <div class="day-card">
        <%= image_tag "cloud.svg", class:"weather-icon" %>
        <div class="day-card-day">Thursday</div>
        <div>32&deg;</div>
      </div>

      <div class="day-card">
        <%= image_tag "cloud.svg", class:"weather-icon" %>
        <div class="day-card-day">Friday</div>
        <div>32&deg;</div>
      </div>

      <div class="day-card">
        <%= image_tag "cloud.svg", class:"weather-icon" %>
        <div class="day-card-day">Saturday</div>
        <div>32&deg;</div>
      </div>

      <div class="day-card">
        <%= image_tag "cloud.svg", class:"weather-icon" %>
        <div class="day-card-day">Sunday</div>
        <div>32&deg;</div>
      </div>

  </section>

  <template id="day-card-template">
      <div class="day-card">
        <img data-icon class="weather-icon" />
        <div class="day-card-day" data-date></div>
        <div><span data-temp></span><span>&deg;</span></div>
      </div>
    </template>

</div>

  <div class="top-section">
    <h1 class="gardens-heading">My Gardens</h1>
    <div class="add-garden-button">
      <%= link_to "Create New Garden", new_garden_path, class: "btn btns-primary" %>
    </div>
  </div>
  <% @gardens.each do |garden| %>
      <% border_images = ["plants_1.jpg", "plants_2.jpg", "plants_3.jpg", "plants_4.jpg", "plants_5.jpg", "plants_6.jpg", "plants_7.jpg", "plants_8.jpg", "plants_9.jpg", "plants_10.jpg", "plants_11.jpg", "plants_15.jpg", "plants_16.jpg", "plants_18.jpg", "plants_19.jpg", "plants_20.jpg", "plants_21.jpg", "plants_22.jpg", "plants_23.jpg"] %>
      <% border_image = border_images.sample %>
      <div class="card" style="background: url(<%= asset_path border_image %>); background-size: cover;">
        <div class="garden-card">
            <div class="garden-title-and-buttons">
                <h5 class="garden-card-title"><%= garden.name %></h5>
                <div class="button-container">
                    <%= link_to "View", garden_path(garden), class: "btn btns-primary" %>
                    <%= link_to "Edit", edit_garden_path(garden), class: "btn btns-secondary" %>
                </div>
            </div>
            <div class="garden-card-body d-flex justify-content-between">
                <div class="garden-details">
                    <p class="garden-card-text">Size: <%= garden.size %>m2</p>
                    <p class="garden-card-text">Location: <%= garden.location %></p>
                    <p class="garden-card-text"><%= garden.outside ? 'Outside' : 'Inside' %></p>
                </div>

                <% sunlight = garden.sunlight || 0 %>
                <% closest_10 = (sunlight / 10.0).round * 10 %>
                <% image_path = "#{closest_10}_sunlight.png" %>

                <div class="sun-icon-container">
                    <%= image_tag image_path, alt: "sunlight icon", class: "sun-icon" %>
                </div>
            </div>
        </div>
    </div>


  <% end %>
</div>

<%= javascript_pack_tag "main" %>

app/views/gardens/new.html.erb
<div class="main-container">
  <h1 class="plant-heading">Create Your Garden</h1>

  <%= form_for @garden, html: { class: 'garden-form' } do |f| %>
    <div class="form-group">
      <%= f.label :name, "Garden Name", class: 'form-label' %>
      <%= f.text_field :name, class: 'form-input', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :location, "Location", class: 'form-label' %>
      <%= f.text_field :location, class: 'form-input', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :outside, "Inside/Outside", class: 'form-label' %>
      <%= f.select :outside, ["Inside", "Outside"], class: 'form-select', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :size, "Garden Size (m2)", class: 'form-label' %>
      <%= f.number_field :size, step: "0.01", class: 'form-input', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :sunlight, "Sunlight Percentage (%)", class: 'form-label' %>
      <%= f.number_field :sunlight, step: "10", class: 'form-input', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :additional_info, "Additional Info", class: 'form-label' %>
      <%= f.text_field :additional_info, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= f.submit "Create Garden", class: 'form-submit' %>
    </div>
  <% end %>
  <%= link_to "Back", gardens_path, class: "back-button" %>
</div>

app/views/gardens/show.html.erb
<div class="main-container">
  <%= link_to image_tag('back-icon.png', size: '30x30'), gardens_path, class: "back-button fixed" %>
  <div class="plant-container">
    <% if @plants_for_dropdown.any? %>
      <div class="container-light-green">
        <h3>Plant Doctor:</h3>
        <%= form_with url: garden_path(@garden), method: :get, id: "plant-doctor-form" do |f| %>
        <%= f.select :plant_name, @plants_for_dropdown, prompt: "Select a plant", class: "form-field" %>
        <%= f.text_field :issue, placeholder: "Describe the problem", class: "form-field form-field-wide" %>
        <%= f.submit "Get Advice", class: "shdw-btn" %>
      <% end %>
        <% if @response %>
          <div class="container-dark-green">
            <h4>Advice:</h4>
            <p class="advice-text"><%= @response.join("\n").html_safe %></p>
            <%= link_to "Clear", :back, class: "btn btn-primary btn-green" %>
          </div>
        <% end %>
      </div>
    <% end %>
    <% border_images = ["plants_1.jpg", "plants_2.jpg", "plants_3.jpg", "plants_4.jpg", "plants_5.jpg", "plants_6.jpg", "plants_7.jpg", "plants_8.jpg", "plants_9.jpg", "plants_10.jpg", "plants_11.jpg", "plants_15.jpg", "plants_16.jpg", "plants_18.jpg", "plants_19.jpg", "plants_20.jpg", "plants_21.jpg", "plants_22.jpg", "plants_23.jpg"] %>
    <% border_image = asset_path(border_images.sample) %>
    <div class="garden-wrapper" style="background-image: url(<%= border_image %>);">
      <div class="row">
        <div class="col">
          <div class="garden-plants-section">
            <h1 class="grdn-name"><%= @garden.name %></h1>
            <% if @garden %>
              <p>Garden Size: <%= @garden.size %> m2</p>
              <p>Sunlight Percentage: <%= @garden.sunlight %> %</p>
          </div>
            <!-- Display garden plants -->
            <div class="garden-plants-section">
              <h2 class="text-center">My Plants</h2>
              <div class="row">
                <% @garden_plants.each do |plant| %>
                  <div class="col-md-3">
                    <div class="plant-card">
                      <%= link_to page_path(plant), data: { turbo: :false } do %><%= image_tag plant.plant_image, class: "plant-card-img" %><% end %>
                      <div class="plant-card-body">
                        <h2 class="plant-card-title"><%= plant.plant_name %></h2>
                        <%= button_to "Remove", remove_from_garden_garden_path(garden_id: @garden.id, plant_id: plant.id), method: :delete, class: "remove-button" %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="main-container">
    <div class="plant-container">
      <div class="row">
        <div class="col">
        <h1 class="text-center">Add Some Plants!</h1>
          <div class="row justify-content-center">
            <div class="col-sm-8 my-3">
              <%= form_with url: garden_path(@garden), method: :get, class: "d-flex" do %>
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Type a keyword" %>
                <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
          <!-- Filters -->
          <div class="filter-buttons">
            <%= link_to "All", garden_path(@garden, category: nil), class: "btn btn-primary filter-button #{params[:category].blank? ? "active" : ""}" %>
            <%= link_to "Fruits", garden_path(@garden, category: "fruit"), class: "btn btn-primary filter-button #{params[:category] == "fruits" ? "active" : ""}" %>
            <%= link_to "Vegetables", garden_path(@garden, category: "vegetable"), class: "btn btn-primary filter-button #{params[:category] == "vegetables" ? "active" : ""}" %>
            <%= link_to "Flowers", garden_path(@garden, category: "flower"), class: "btn btn-primary filter-button #{params[:category] == "flowers" ? "active" : ""}" %>
            <%= link_to "Herbs", garden_path(@garden, category: "herb"), class: "btn btn-primary filter-button #{params[:category] == "herbs" ? "active" : ""}" %>
            <%= link_to "Recommended", garden_path(@garden, category: "recommended"), class: "btn btn-primary filter-button #{params[:category] == "recommended" ? "active" : ""}" %>
          </div>
        </div>
      </div>
      <div class="row">
        <% @plants.each do |plant| %>
          <div class="col-md-3">
            <div class="plant-card">
              <%= link_to page_path(plant), data: { turbo: :false } do %><%= image_tag plant.plant_image, class: "plant-card-img" %><% end %>
              <div class="plant-card-body">
                <h2 class="plant-card-title"><%= plant.plant_name %></h2>
                <%= button_to "Add to Garden", add_to_garden_garden_path(garden_id: @garden.id, plant_id: plant.id), method: :post, class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>